import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding Easy-Cart database in Indian Rupees (INR) with Dyson products...');

  // Clean existing data
  await prisma.notification.deleteMany();
  await prisma.review.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.wishlistItem.deleteMany();
  await prisma.wishlist.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.productVariant.deleteMany();
  await prisma.productImage.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.address.deleteMany();
  await prisma.user.deleteMany();
  await prisma.coupon.deleteMany();

  // 1. Password Hashing
  const adminPassword = await bcrypt.hash('admin123', 10);
  const userPassword = await bcrypt.hash('user123', 10);

  // 2. Create Users
  const admin = await prisma.user.create({
    data: {
      name: 'Store Admin',
      email: 'admin@easycart.com',
      password: adminPassword,
      phone: '+91 98765 43210',
      role: 'ADMIN',
      image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    },
  });

  const customer1 = await prisma.user.create({
    data: {
      name: 'Alex Johnson',
      email: 'user@easycart.com',
      password: userPassword,
      phone: '+91 98123 45678',
      role: 'CUSTOMER',
      image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    },
  });

  const customer2 = await prisma.user.create({
    data: {
      name: 'Sophia Martinez',
      email: 'sophia@example.com',
      password: userPassword,
      phone: '+91 97654 32109',
      role: 'CUSTOMER',
      image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    },
  });

  // 3. Create Sample Addresses
  await prisma.address.create({
    data: {
      userId: customer1.id,
      fullName: 'Alex Johnson',
      phone: '+91 98123 45678',
      streetAddress: 'Flat 402, Green Glen Layout, Bellandur',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560103',
      country: 'India',
      isDefault: true,
    },
  });

  // 4. Create Coupons (Values in INR)
  await prisma.coupon.createMany({
    data: [
      {
        code: 'EASY20',
        discountType: 'PERCENTAGE',
        discountValue: 20,
        minOrderAmount: 1499,
        maxDiscount: 2000,
        isActive: true,
      },
      {
        code: 'WELCOME10',
        discountType: 'PERCENTAGE',
        discountValue: 10,
        minOrderAmount: 999,
        maxDiscount: 1000,
        isActive: true,
      },
      {
        code: 'FREESHIP',
        discountType: 'FIXED',
        discountValue: 149,
        minOrderAmount: 799,
        isActive: true,
      },
    ],
  });

  // 5. Create Categories
  const categoriesData = [
    {
      name: 'Electronics',
      slug: 'electronics',
      description: 'Gadgets, smartphones, laptops, audio gear and smart home devices.',
      image: 'https://images.unsplash.com/photo-1498049860654-af1a5c566876?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Fashion',
      slug: 'fashion',
      description: 'Trendy clothing, apparel, footwear and stylish outfits.',
      image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Beauty',
      slug: 'beauty',
      description: 'Skincare, cosmetics, perfumes and self-care essentials.',
      image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Home & Kitchen',
      slug: 'home-kitchen',
      description: 'Furniture, appliances, cookware, decor and smart living tools.',
      image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Grocery',
      slug: 'grocery',
      description: 'Fresh organic produce, snacks, beverages and daily staples.',
      image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Sports',
      slug: 'sports',
      description: 'Fitness equipment, sportswear, outdoor gear and athletic accessories.',
      image: 'https://images.unsplash.com/photo-1517649763962-0c623266010b?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Accessories',
      slug: 'accessories',
      description: 'Watches, jewelry, bags, wallets, sunglasses and tech accessories.',
      image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=600&auto=format&fit=crop&q=80',
    },
    {
      name: 'Books',
      slug: 'books',
      description: 'Bestselling novels, educational textbooks, self-help and comics.',
      image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80',
    },
  ];

  const createdCategories: Record<string, any> = {};
  for (const cat of categoriesData) {
    const created = await prisma.category.create({ data: cat });
    createdCategories[cat.slug] = created;
  }

  // 6. Create 60 Products (including official DYSON products!) in Indian Rupees (INR)
  const products = [
    // DYSON PRODUCTS
    {
      name: 'Dyson Supersonic™ Hair Dryer (Special Edition Strawberry Bronze)',
      slug: 'dyson-supersonic-hair-dryer-strawberry-bronze',
      description: 'Fast drying with intelligent heat control to protect natural shine. Driven by the Dyson digital motor V9 with 5 styling attachments including Flyaway attachment.',
      specifications: 'Motor: Dyson V9 110,000rpm | Airflow: 41 liters/sec | Heat Settings: 4 precise settings (28°C to 100°C) | Power: 1600W | Weight: 680g',
      price: 34900,
      originalPrice: 38900,
      discountPercent: 10,
      stock: 25,
      rating: 4.95,
      reviewCount: 380,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 4),
      brand: 'Dyson',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Strawberry Bronze / Blush Pink', 'Iron / Fuchsia', 'Nickel / Copper'],
      sizes: [],
    },
    {
      name: 'Dyson Airwrap™ Multi-Styler Complete Long',
      slug: 'dyson-airwrap-multi-styler-complete-long',
      description: 'Curl, shape, smooth and hide flyaways with no extreme heat. Enhanced Coanda airflow attracts and self-wraps hair in both directions for voluminous curls.',
      specifications: 'Technology: Coanda Airflow | Power: 1300W | Attachments: 30mm & 40mm barrels, Firm & Soft smoothing brushes, Coanda smoothing dryer',
      price: 49900,
      originalPrice: 54900,
      discountPercent: 9,
      stock: 18,
      rating: 4.98,
      reviewCount: 420,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'Dyson',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Vinca Blue / Rosé', 'Copper / Bright Nickel'],
      sizes: [],
    },
    {
      name: 'Dyson V15 Detect™ Cordless Vacuum Cleaner',
      slug: 'dyson-v15-detect-cordless-vacuum-cleaner',
      description: 'Dyson\'s most powerful, intelligent cordless vacuum. Illumination reveals invisible microscopic dust on hard floors while piezo sensor scientific proof of deep clean shows on LCD screen.',
      specifications: 'Suction Power: 230AW | Runtime: Up to 60 Mins | Filtration: 99.99% down to 0.3 microns | Weight: 3.1kg',
      price: 62900,
      originalPrice: 68900,
      discountPercent: 9,
      stock: 14,
      rating: 4.92,
      reviewCount: 290,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 5),
      brand: 'Dyson',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Yellow / Nickel'],
      sizes: [],
    },
    {
      name: 'Dyson Purifier Cool™ Gen1 Air Purifier Fan',
      slug: 'dyson-purifier-cool-gen1-air-purifier-fan',
      description: 'Automatically senses, captures, and traps pollutants for cleaner air. HEPA H13 filtration removes 99.95% of particles as small as 0.1 microns with Air Multiplier™ technology.',
      specifications: 'Filter: Sealed HEPA H13 + Carbon | Airflow: 290 liters/sec | Oscillation: 350° | Night Mode: Quietest 31.5dB',
      price: 39900,
      originalPrice: 44900,
      discountPercent: 11,
      stock: 20,
      rating: 4.88,
      reviewCount: 195,
      isFeatured: true,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'Dyson',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['White / Silver'],
      sizes: [],
    },

    // Electronics (INR Prices)
    {
      name: 'Aura Studio Wireless Noise-Canceling Headphones',
      slug: 'aura-studio-wireless-headphones',
      description: 'Experience immersive high-fidelity audio with active noise cancellation, 40-hour battery life, ergonomic memory-foam earcups, and ultra-fast Bluetooth 5.3 connectivity.',
      specifications: 'Driver: 40mm Neodymium | Battery: 40 hours | Bluetooth: 5.3 | ANC: Active Hybrid | Weight: 250g',
      price: 14999,
      originalPrice: 18999,
      discountPercent: 21,
      stock: 45,
      rating: 4.8,
      reviewCount: 128,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 3),
      brand: 'AuraSound',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Matte Black', 'Silver Grey', 'Midnight Navy'],
      sizes: [],
    },
    {
      name: 'UltraView 4K OLED Smart Watch Pro',
      slug: 'ultraview-4k-oled-smart-watch-pro',
      description: 'Track your health, fitness metrics, sleep cycles, and heart rate with precision. Always-on AMOLED display, built-in GPS, water resistance up to 50m, and 7-day battery.',
      specifications: 'Display: 1.4" AMOLED | Battery: 7 Days | Water Resistance: 5ATM | Sensors: SpO2, Heart Rate, ECG',
      price: 22900,
      originalPrice: 26900,
      discountPercent: 15,
      stock: 30,
      rating: 4.7,
      reviewCount: 94,
      isFeatured: true,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'PulseTech',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Titanium Grey', 'Rose Gold', 'Stealth Black'],
      sizes: ['40mm', '44mm'],
    },
    {
      name: 'ZenBook Slim Pro 15.6" Laptop',
      slug: 'zenbook-slim-pro-15-laptop',
      description: 'Ultra-thin lightweight aluminum laptop featuring Intel Core i7 processor, 16GB DDR5 RAM, 1TB NVMe SSD, and vivid FHD IPS display designed for professionals and creators.',
      specifications: 'CPU: Intel i7-13700H | RAM: 16GB | Storage: 1TB SSD | Display: 15.6" 120Hz IPS | Weight: 1.4kg',
      price: 94999,
      originalPrice: 114999,
      discountPercent: 17,
      stock: 12,
      rating: 4.9,
      reviewCount: 62,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'AsusTech',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Celestial Blue', 'Space Grey'],
      sizes: ['16GB / 1TB', '32GB / 2TB'],
    },
    {
      name: 'SonicBoom Portable Waterproof Bluetooth Speaker',
      slug: 'sonicboom-portable-waterproof-speaker',
      description: '360-degree room-filling stereo sound with deep bass reflex ports. IPX7 waterproof rating, 24-hour continuous playback, and built-in powerbank function.',
      specifications: 'Power Output: 40W | Battery: 24h Playtime | Waterproof: IPX7 | Connectivity: Bluetooth 5.2 & AUX',
      price: 5999,
      originalPrice: 7999,
      discountPercent: 25,
      stock: 65,
      rating: 4.6,
      reviewCount: 215,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 2),
      brand: 'AuraSound',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Ocean Teal', 'Crimson Red', 'Jet Black'],
      sizes: [],
    },
    {
      name: 'ErgoPro Mechanical Wireless Gaming Keyboard',
      slug: 'ergopro-mechanical-wireless-gaming-keyboard',
      description: 'Customizable RGB backlighting with hot-swappable tactile mechanical switches. Tri-mode connection (Bluetooth 5.1, 2.4GHz wireless, USB-C wired) with 4000mAh battery.',
      specifications: 'Switches: Hot-swappable Tactile Brown | Battery: 4000mAh | Backlight: 16.8M RGB',
      price: 9999,
      originalPrice: 12999,
      discountPercent: 23,
      stock: 40,
      rating: 4.8,
      reviewCount: 110,
      isFeatured: true,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'PulseTech',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Cyber Black', 'Retro Chalk'],
      sizes: [],
    },
    {
      name: 'VisionX 4K Ultra HD Streaming Camera & Webcam',
      slug: 'visionx-4k-ultra-hd-webcam',
      description: 'Professional 4K 60FPS streaming webcam featuring AI-powered auto-framing, dual omnidirectional noise-canceling microphones, and privacy shutter lens.',
      specifications: 'Resolution: 4K UHD 60fps | Lens: HDR Glass | Mic: Dual Stereo Noise Reduction',
      price: 8499,
      originalPrice: 10999,
      discountPercent: 23,
      stock: 35,
      rating: 4.7,
      reviewCount: 86,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 4),
      brand: 'PulseTech',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1588702547923-7093a6c3ba33?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Midnight Black'],
      sizes: [],
    },
    {
      name: 'BassPulse True Wireless Earbuds with ANC Case',
      slug: 'basspulse-true-wireless-earbuds-anc',
      description: 'Crystal clear active noise cancellation with 10mm graphene drivers. IPX5 sweat resistance and compact wireless charging case providing 32 hours total playback.',
      specifications: 'Drivers: 10mm Graphene | Battery: 8h Earbuds + 24h Case | Waterproof: IPX5',
      price: 4999,
      originalPrice: 6999,
      discountPercent: 29,
      stock: 85,
      rating: 4.6,
      reviewCount: 190,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'AuraSound',
      categorySlug: 'electronics',
      images: [
        'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Pure White', 'Matte Black', 'Lavender'],
      sizes: [],
    },

    // Fashion (INR Prices)
    {
      name: 'Classic Vintage Leather Biker Jacket',
      slug: 'classic-vintage-leather-biker-jacket',
      description: 'Handcrafted genuine lambskin leather jacket with asymmetrical zip closure, quilted shoulder padding, and soft satin lining for ultimate style and comfort.',
      specifications: 'Material: 100% Genuine Lambskin | Lining: Polyester Satin | Care: Professional Leather Clean Only',
      price: 12999,
      originalPrice: 16999,
      discountPercent: 24,
      stock: 25,
      rating: 4.9,
      reviewCount: 88,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'UrbanCraft',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Classic Black', 'Cognac Brown'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    },
    {
      name: 'Breathable Knit Running Performance Sneakers',
      slug: 'breathable-knit-running-sneakers',
      description: 'Lightweight responsive cushioning paired with engineered stretch-knit upper for maximum airflow and impact absorption during high-intensity runs or daily wear.',
      specifications: 'Upper: Engineered Mesh | Midsole: EVA Foam | Outsole: Non-slip Rubber | Drop: 8mm',
      price: 6999,
      originalPrice: 8999,
      discountPercent: 22,
      stock: 80,
      rating: 4.7,
      reviewCount: 310,
      isFeatured: true,
      isBestSeller: false,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 4),
      brand: 'AeroStep',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Bright Red', 'Core White', 'Triple Black'],
      sizes: ['7', '8', '9', '10', '11', '12'],
    },
    {
      name: 'Organic Cotton Minimalist Oversized Hoodie',
      slug: 'organic-cotton-minimalist-oversized-hoodie',
      description: 'Ultra-soft 400 GSM heavyweight organic french terry cotton hoodie featuring a kangaroo pouch pocket, double-lined hood, and relaxed modern drop-shoulder silhouette.',
      specifications: 'Material: 100% Organic Cotton | Weight: 400 GSM | Fit: Relaxed Oversized',
      price: 3999,
      originalPrice: 5499,
      discountPercent: 27,
      stock: 110,
      rating: 4.8,
      reviewCount: 175,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'NordicThread',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Oatmeal Beige', 'Washed Black', 'Sage Green'],
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      name: 'Slim-Fit Stretch Denim Tailored Jeans',
      slug: 'slim-fit-stretch-denim-tailored-jeans',
      description: 'Premium indigo dyed cotton blended with 2% elastane for unrestricted flex. Classic 5-pocket styling with reinforced stress points and custom brass rivets.',
      specifications: 'Material: 98% Cotton, 2% Elastane | Wash: Vintage Medium Indigo | Closure: Button Fly',
      price: 4499,
      originalPrice: 5999,
      discountPercent: 25,
      stock: 50,
      rating: 4.5,
      reviewCount: 92,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'DenimCo',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Dark Wash', 'Light Wash', 'Black Wash'],
      sizes: ['30x32', '32x32', '34x32', '36x32'],
    },
    {
      name: 'Water-Resistant Outdoor Windbreaker Jacket',
      slug: 'water-resistant-outdoor-windbreaker-jacket',
      description: 'Lightweight packable storm-proof hoody with sealed zippers and breathable underarm mesh vents. Folds into its own interior pocket for compact hiking and travel.',
      specifications: 'Shell: 100% Ripstop Nylon DWR | Water Rating: 10,000mm | Weight: 280g',
      price: 5499,
      originalPrice: 6999,
      discountPercent: 21,
      stock: 60,
      rating: 4.7,
      reviewCount: 140,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 3),
      brand: 'AeroStep',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Mustard Yellow', 'Forest Green', 'Charcoal'],
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      name: 'Tailored Italian Wool Blend Blazer',
      slug: 'tailored-italian-wool-blend-blazer',
      description: 'Single-breasted sharp modern jacket woven from Italian virgin wool blend. Features notch lapels, dual rear vents, and interior passport pocket.',
      specifications: 'Material: 70% Wool, 30% Polyester | Cut: Modern Slim | Dry Clean Only',
      price: 11999,
      originalPrice: 15999,
      discountPercent: 25,
      stock: 20,
      rating: 4.9,
      reviewCount: 65,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'UrbanCraft',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Navy Blue', 'Charcoal Grey'],
      sizes: ['38R', '40R', '42R', '44R'],
    },
    {
      name: 'Chunky Platform Retro Canvas High-Top Sneakers',
      slug: 'chunky-platform-retro-canvas-high-tops',
      description: 'Vintage high-top canvas sneaker updated with a 1.5-inch vulcanized platform rubber midsole and OrthoLite memory foam footbed for elevated daily comfort.',
      specifications: 'Upper: 12oz Heavy Canvas | Sole: Vulcanized Rubber | Platform: 1.5 inches',
      price: 4999,
      originalPrice: 5999,
      discountPercent: 17,
      stock: 75,
      rating: 4.6,
      reviewCount: 160,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'AeroStep',
      categorySlug: 'fashion',
      images: [
        'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Off-White', 'Classic Black'],
      sizes: ['6', '7', '8', '9', '10'],
    },

    // Beauty (INR Prices)
    {
      name: 'Radiance Botanical Hydrating Serum',
      slug: 'radiance-botanical-hydrating-serum',
      description: 'Infused with Hyaluronic Acid, Niacinamide, and organic botanical extracts to lock in moisture, reduce fine lines, and restore a youthful luminous glowing complexion.',
      specifications: 'Volume: 50ml | Key Ingredients: Hyaluronic Acid 2%, Niacinamide 5%, Vitamin C | Skin Type: All',
      price: 2499,
      originalPrice: 3199,
      discountPercent: 22,
      stock: 90,
      rating: 4.9,
      reviewCount: 240,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'GlowGoddess',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1608248597261-833258657640?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['30ml', '50ml'],
    },
    {
      name: 'Velvet Matte Long-Wear Lipstick Collection',
      slug: 'velvet-matte-long-wear-lipstick-collection',
      description: 'Highly pigmented, featherweight matte lipstick formula infused with Shea Butter and Vitamin E for 12-hour comfortable wear without drying your lips.',
      specifications: 'Finish: Velvet Matte | Weight: 3.5g | Cruelty-Free & Vegan Formula',
      price: 1899,
      originalPrice: 2299,
      discountPercent: 17,
      stock: 120,
      rating: 4.7,
      reviewCount: 155,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 1),
      brand: 'LuxeLuxe',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Ruby Red', 'Nude Pink', 'Plum Berry'],
      sizes: [],
    },
    {
      name: 'Organic Argan Oil Hair Repair Treatment Mask',
      slug: 'organic-argan-oil-hair-repair-treatment-mask',
      description: 'Deep conditioning treatment mask enriched with cold-pressed Moroccan Argan Oil and Keratin proteins to repair split ends, eliminate frizz, and add silky shine.',
      specifications: 'Volume: 250ml | Free from Sulfates, Parabens, and Phthalates',
      price: 1999,
      originalPrice: 2499,
      discountPercent: 20,
      stock: 75,
      rating: 4.8,
      reviewCount: 188,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'SilkBotanicals',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['250ml', '500ml'],
    },
    {
      name: 'Rose Quartz Facial Roller & Gua Sha Set',
      slug: 'rose-quartz-facial-roller-gua-sha-set',
      description: 'Hand-carved 100% natural Brazilian Rose Quartz facial tools to stimulate lymphatic drainage, ease facial tension, improve skin elasticity, and enhance serum absorption.',
      specifications: 'Material: 100% Natural Rose Quartz | Includes: Dual-ended Roller + Heart-shaped Gua Sha',
      price: 1499,
      originalPrice: 2199,
      discountPercent: 32,
      stock: 140,
      rating: 4.6,
      reviewCount: 89,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'GlowGoddess',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },
    {
      name: 'Ultra-Hydrating Botanical Night Repair Moisturizer',
      slug: 'ultra-hydrating-botanical-night-repair-moisturizer',
      description: 'Rich overnight cream packed with 5-ceramide complex, squalane, and triple peptides to lock in moisture and visibly plump skin texture while you sleep.',
      specifications: 'Volume: 50g | Dermatologist Tested | Non-Comedogenic',
      price: 2999,
      originalPrice: 3899,
      discountPercent: 23,
      stock: 65,
      rating: 4.9,
      reviewCount: 170,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'GlowGoddess',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },
    {
      name: 'Mineral Sunscreen Lotion SPF 50 Broad Spectrum',
      slug: 'mineral-sunscreen-lotion-spf-50',
      description: '100% Non-nano Zinc Oxide mineral sunscreen providing broad spectrum UVA/UVB protection. Ocean reef safe, water resistant up to 80 minutes, with invisible matte finish.',
      specifications: 'SPF: 50 Broad Spectrum | Active: 12% Zinc Oxide | Volume: 80ml',
      price: 1499,
      originalPrice: 1899,
      discountPercent: 21,
      stock: 110,
      rating: 4.7,
      reviewCount: 210,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'GlowGoddess',
      categorySlug: 'beauty',
      images: [
        'https://images.unsplash.com/photo-1567928256057-a9a7a63725b8?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },

    // Home & Kitchen (INR Prices)
    {
      name: 'Precision Barista Automatic Espresso Machine',
      slug: 'precision-barista-automatic-espresso-machine',
      description: 'Italian 19-bar pressure pump system delivering rich crema coffee. Features integrated conical burr grinder, microfoam milk steamer wand, and digital touch interface.',
      specifications: 'Pressure: 19-Bar | Bean Hopper: 250g | Water Tank: 2.0L | Power: 1450W',
      price: 38999,
      originalPrice: 49999,
      discountPercent: 22,
      stock: 18,
      rating: 4.9,
      reviewCount: 312,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 5),
      brand: 'Caffeto',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1517668808822-9ebe02f2a6e8?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Brushed Stainless Steel', 'Matte Black'],
      sizes: [],
    },
    {
      name: 'Cast Iron Enamelled Dutch Oven (5.5 Quart)',
      slug: 'cast-iron-enamelled-dutch-oven-5-quart',
      description: 'Superior heat distribution and retention for braising, baking artisan sourdough bread, roasting meats, and simmering rich stews. Compatible with all cooktops including induction.',
      specifications: 'Capacity: 5.5 Quarts | Oven Safe: Up to 500°F (260°C) | Material: Enamelled Cast Iron',
      price: 8999,
      originalPrice: 11999,
      discountPercent: 25,
      stock: 35,
      rating: 4.8,
      reviewCount: 142,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'CulinaryPro',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1584992236310-6edddc08acff?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Flame Red', 'Deep Navy', 'Sage Green'],
      sizes: ['5.5 Quart', '7.0 Quart'],
    },
    {
      name: 'Smart Air Purifier with True HEPA Filter',
      slug: 'smart-air-purifier-true-hepa-filter',
      description: 'Cleans up to 500 sq ft in 12 minutes. 3-stage filtration captures 99.97% of airborne particles including dust, pollen, pet dander, and smoke. Ultra-quiet sleep mode.',
      specifications: 'Coverage: 500 sq ft | Filter: H13 True HEPA | Noise Level: 22dB - 50dB | App Control: Wi-Fi',
      price: 11999,
      originalPrice: 14999,
      discountPercent: 20,
      stock: 40,
      rating: 4.7,
      reviewCount: 205,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'BreathePure',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Pure White', 'Charcoal Grey'],
      sizes: [],
    },
    {
      name: 'Ergonomic Memory Foam Contour Pillow',
      slug: 'ergonomic-memory-foam-contour-pillow',
      description: 'Relieves neck and shoulder pain with cervical orthopedic contouring. Breathable bamboo fabric cover is removable, hypoallergenic, and machine washable.',
      specifications: 'Fill: High-Density Viscoelastic Foam | Cover: 40% Bamboo, 60% Polyester',
      price: 2499,
      originalPrice: 3199,
      discountPercent: 22,
      stock: 100,
      rating: 4.6,
      reviewCount: 298,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'DreamSlumber',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['White'],
      sizes: ['Standard', 'King'],
    },
    {
      name: 'Multi-Function Digital Air Fryer Oven (10 Liter)',
      slug: 'multi-function-digital-air-fryer-oven',
      description: 'Crisp food with 85% less oil using rapid 360° thermo-cyclone air technology. 12 one-touch cooking presets with glass view window and motorized rotisserie spit.',
      specifications: 'Capacity: 10 Liters | Power: 1700W | Temperature Range: 100°F - 400°F',
      price: 9999,
      originalPrice: 12999,
      discountPercent: 23,
      stock: 30,
      rating: 4.85,
      reviewCount: 220,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 3),
      brand: 'CulinaryPro',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Stainless Black'],
      sizes: [],
    },
    {
      name: 'Bamboo Knife Block & Japanese Chef Knife Set (6 Piece)',
      slug: 'bamboo-knife-block-japanese-chef-knife-set',
      description: 'Precision forged high-carbon German X50CrMoV15 stainless steel razor-sharp blades. Ergonomic pakkawood handles stored in a natural acacia magnetic wooden block.',
      specifications: 'Steel: German X50CrMoV15 | Hardness: 56+ HRC | Set Includes: 8" Chef, 8" Bread, 7" Santoku, Utility, Paring, Block',
      price: 7499,
      originalPrice: 9999,
      discountPercent: 25,
      stock: 45,
      rating: 4.9,
      reviewCount: 180,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'CulinaryPro',
      categorySlug: 'home-kitchen',
      images: [
        'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },

    // Grocery (INR Prices)
    {
      name: 'Organic Cold-Pressed Extra Virgin Olive Oil (1L)',
      slug: 'organic-cold-pressed-extra-virgin-olive-oil-1l',
      description: 'Single-estate estate harvested Koroneiki olives cold-extracted within 4 hours. Rich in polyphenols and antioxidants with a delicate grassy peppery finish.',
      specifications: 'Volume: 1 Litre | Acidity: < 0.3% | Origin: Kalamata, Greece | Certification: USDA Organic',
      price: 1899,
      originalPrice: 2299,
      discountPercent: 17,
      stock: 150,
      rating: 4.9,
      reviewCount: 410,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'OlympusGroves',
      categorySlug: 'grocery',
      images: [
        'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['500ml', '1 Litre'],
    },
    {
      name: 'Artisan Single-Origin Whole Bean Coffee (1kg)',
      slug: 'artisan-single-origin-whole-bean-coffee-1kg',
      description: '100% Arabica shade-grown coffee beans freshly medium-roasted in micro-batches. Flavor profile exhibits notes of dark chocolate, toasted hazelnut, and caramel.',
      specifications: 'Weight: 1kg | Roast Level: Medium Roast | Origin: Ethiopian Yirgacheffe',
      price: 2199,
      originalPrice: 2699,
      discountPercent: 19,
      stock: 85,
      rating: 4.8,
      reviewCount: 164,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 2),
      brand: 'BeanCraft',
      categorySlug: 'grocery',
      images: [
        'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['250g', '1kg'],
    },
    {
      name: 'Raw Unfiltered Wildflower Honey Jar (500g)',
      slug: 'raw-unfiltered-wildflower-honey-jar-500g',
      description: 'Directly sourced from sustainable family apiaries. Unpasteurized pure honey packed with natural enzymes, pollen, and rich blossom fragrance.',
      specifications: 'Weight: 500g | 100% Pure Raw Honey | Non-GMO Verified',
      price: 999,
      originalPrice: 1299,
      discountPercent: 23,
      stock: 120,
      rating: 4.9,
      reviewCount: 118,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'HoneyBeeFarm',
      categorySlug: 'grocery',
      images: [
        'https://images.unsplash.com/photo-1587049352847-4a222e784d38?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },
    {
      name: 'Gourmet Organic Dark Chocolate Bar Variety Pack',
      slug: 'gourmet-organic-dark-chocolate-bar-variety-pack',
      description: 'Pack of 6 artisanal 70%+ cocoa bean-to-bar dark chocolates featuring Sea Salt, Sea Salt & Almonds, Espresso Crisp, Orange Peel, Mint, and Classic Dark.',
      specifications: 'Quantity: 6 Bars x 80g | Cocoa: 70% to 85% Fairtrade Organic',
      price: 1499,
      originalPrice: 1899,
      discountPercent: 21,
      stock: 95,
      rating: 4.7,
      reviewCount: 88,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'ChocoArtisan',
      categorySlug: 'grocery',
      images: [
        'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },
    {
      name: 'Artisan Organic Matcha Green Tea Powder (100g)',
      slug: 'artisan-organic-matcha-green-tea-powder',
      description: 'First harvest Uji ceremonial grade stone-ground Japanese green tea powder. Vibrant jade green color bursting with L-theanine and clean antioxidant energy.',
      specifications: 'Weight: 100g | Grade: Uji Ceremonial 1st Harvest | Origin: Kyoto, Japan',
      price: 1999,
      originalPrice: 2499,
      discountPercent: 20,
      stock: 70,
      rating: 4.95,
      reviewCount: 280,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'OlympusGroves',
      categorySlug: 'grocery',
      images: [
        'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: [],
    },

    // Sports (INR Prices)
    {
      name: 'Anti-Tear Extra Thick Non-Slip Yoga Mat',
      slug: 'anti-tear-extra-thick-non-slip-yoga-mat',
      description: '6mm eco-friendly TPE foam provides dense cushion protection for knees and joints. Dual-sided non-slip texture ensures grip during strenuous hot yoga workouts.',
      specifications: 'Thickness: 6mm | Material: Eco TPE | Dimensions: 72" x 24" | Carrying Strap Included',
      price: 2199,
      originalPrice: 2899,
      discountPercent: 24,
      stock: 110,
      rating: 4.8,
      reviewCount: 350,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'ZenFit',
      categorySlug: 'sports',
      images: [
        'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Plum Purple', 'Midnight Blue', 'Sage Green'],
      sizes: [],
    },
    {
      name: 'Adjustable Quick-Select Dumbbell Pair (5-52.5 lbs)',
      slug: 'adjustable-quick-select-dumbbell-pair',
      description: 'Replace 15 sets of weights with a single turn of a dial. Smooth weight adjustment system ranging from 5 to 52.5 lbs per dumbbell in 2.5 lb increments.',
      specifications: 'Weight Range: 5 - 52.5 lbs per dumbbell | Material: Heavy Duty Steel Plates',
      price: 24999,
      originalPrice: 29999,
      discountPercent: 17,
      stock: 22,
      rating: 4.9,
      reviewCount: 180,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 3),
      brand: 'IronStrength',
      categorySlug: 'sports',
      images: [
        'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Black & Red'],
      sizes: [],
    },
    {
      name: 'Insulated Stainless Steel Vacuum Water Bottle (32oz)',
      slug: 'insulated-stainless-steel-water-bottle-32oz',
      description: 'Double-wall vacuum insulation keeps drinks ice cold for 24 hours or piping hot for 12 hours. Sweat-free powder coat finish with leakproof straw lid.',
      specifications: 'Capacity: 32 oz (950ml) | Material: 18/8 Food Grade Stainless Steel | BPA Free',
      price: 1799,
      originalPrice: 2299,
      discountPercent: 22,
      stock: 140,
      rating: 4.7,
      reviewCount: 420,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'HydroPeak',
      categorySlug: 'sports',
      images: [
        'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Matte Black', 'Cobalt Blue', 'Mint Green'],
      sizes: ['24oz', '32oz', '40oz'],
    },
    {
      name: 'Smart Hydration & Fitness Tracker Band',
      slug: 'smart-hydration-fitness-tracker-band',
      description: 'Lightweight fitness band monitoring steps, distance, calories burned, sleep quality, and active heart rate zones with 10-day battery life.',
      specifications: 'Display: 0.96" OLED | Battery: 10 Days | Waterproof: IP68 | Bluetooth 5.0',
      price: 3499,
      originalPrice: 4999,
      discountPercent: 30,
      stock: 65,
      rating: 4.5,
      reviewCount: 112,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'PulseTech',
      categorySlug: 'sports',
      images: [
        'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Black', 'Navy', 'Pink'],
      sizes: [],
    },

    // Accessories (INR Prices)
    {
      name: 'Handmade Italian Full-Grain Leather Wallet',
      slug: 'handmade-italian-full-grain-leather-wallet',
      description: 'Slim bifold wallet with built-in RFID blocking shield technology to protect credit cards from unauthorized scanning. Features 8 card slots and dual cash compartments.',
      specifications: 'Material: Full-Grain Tuscan Leather | RFID Protection: 13.56 MHz | Dimensions: 4.3" x 3.5"',
      price: 3299,
      originalPrice: 4299,
      discountPercent: 23,
      stock: 80,
      rating: 4.9,
      reviewCount: 195,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'ModenaCraft',
      categorySlug: 'accessories',
      images: [
        'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Chestnut Tan', 'Midnight Black', 'Vintage Olive'],
      sizes: [],
    },
    {
      name: 'Polarized Aviator Classic UV400 Sunglasses',
      slug: 'polarized-aviator-classic-uv400-sunglasses',
      description: 'Timeless aviator alloy frame with scratch-resistant polarized TAC lenses providing 100% protection against harmful UVA/UVB rays and reducing glaring glare.',
      specifications: 'Lens: TAC Polarized UV400 | Frame: Corrosion-resistant Monel Alloy | Case Included',
      price: 2799,
      originalPrice: 3999,
      discountPercent: 30,
      stock: 95,
      rating: 4.7,
      reviewCount: 230,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 2),
      brand: 'SolarisSpectacles',
      categorySlug: 'accessories',
      images: [
        'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Gold / Green Lens', 'Black / Grey Lens', 'Silver / Mirror Lens'],
      sizes: [],
    },
    {
      name: 'Canvas Waterproof Laptop Backpack (15.6")',
      slug: 'canvas-waterproof-laptop-backpack-15-inch',
      description: 'Durable waxed canvas computer backpack featuring padded laptop sleeve, anti-theft hidden pocket, external USB charging port, and ergonomic ventilated shoulder straps.',
      specifications: 'Fits Laptops: Up to 15.6" | Material: Waxed Water-Resistant Canvas | Capacity: 24L',
      price: 4499,
      originalPrice: 5999,
      discountPercent: 25,
      stock: 60,
      rating: 4.8,
      reviewCount: 168,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'UrbanCraft',
      categorySlug: 'accessories',
      images: [
        'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Charcoal Grey', 'Khaki Brown', 'Navy Blue'],
      sizes: [],
    },
    {
      name: 'Minimalist Automatic Mechanical Watch',
      slug: 'minimalist-automatic-mechanical-watch',
      description: 'Self-winding Japanese automatic movement with 42-hour power reserve. Domed sapphire glass lens, stainless steel case, and genuine quick-release leather strap.',
      specifications: 'Movement: Automatic Caliber | Glass: Sapphire Crystal | Water Resistance: 50m | Case: 40mm',
      price: 14999,
      originalPrice: 18999,
      discountPercent: 21,
      stock: 25,
      rating: 4.9,
      reviewCount: 77,
      isFeatured: true,
      isBestSeller: false,
      isFlashDeal: false,
      brand: 'Chronos',
      categorySlug: 'accessories',
      images: [
        'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&auto=format&fit=crop&q=80',
      ],
      colors: ['Silver / Black Strap', 'Rose Gold / Brown Strap'],
      sizes: [],
    },

    // Books (INR Prices)
    {
      name: 'Atomic Habits by James Clear (Hardcover)',
      slug: 'atomic-habits-james-clear-hardcover',
      description: 'The definitive revolutionary guide to breaking bad behaviors and building good habits using tiny 1% daily improvements grounded in neuroscience and psychology.',
      specifications: 'Format: Hardcover | Pages: 320 | Publisher: Avery | Language: English',
      price: 599,
      originalPrice: 799,
      discountPercent: 25,
      stock: 200,
      rating: 4.95,
      reviewCount: 1420,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'Penguin Random House',
      categorySlug: 'books',
      images: [
        'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['Hardcover', 'Paperback', 'Kindle'],
    },
    {
      name: 'The Psychology of Money by Morgan Housel',
      slug: 'the-psychology-of-money-morgan-housel',
      description: 'Timeless lessons on wealth, greed, and happiness exploring how human emotions, biases, and behavior govern financial success far more than math and intellect.',
      specifications: 'Format: Paperback | Pages: 252 | Publisher: Harriman House',
      price: 399,
      originalPrice: 499,
      discountPercent: 20,
      stock: 160,
      rating: 4.9,
      reviewCount: 890,
      isFeatured: false,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'Harriman House',
      categorySlug: 'books',
      images: [
        'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['Paperback', 'Hardcover'],
    },
    {
      name: 'Deep Work: Rules for Focused Success by Cal Newport',
      slug: 'deep-work-cal-newport',
      description: 'Master the ability to focus without distraction on demanding cognitive tasks to achieve peak performance, produce rare value, and thrive in an easily distracted world.',
      specifications: 'Format: Paperback | Pages: 304 | Publisher: Grand Central Publishing',
      price: 499,
      originalPrice: 699,
      discountPercent: 28,
      stock: 130,
      rating: 4.85,
      reviewCount: 640,
      isFeatured: false,
      isBestSeller: false,
      isFlashDeal: true,
      flashDealEnd: new Date(Date.now() + 86400000 * 3),
      brand: 'Grand Central Publishing',
      categorySlug: 'books',
      images: [
        'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['Paperback', 'Audiobook'],
    },
    {
      name: 'Designing Data-Intensive Applications by Martin Kleppmann',
      slug: 'designing-data-intensive-applications-martin-kleppmann',
      description: 'The essential architectural reference guide for software engineers analyzing the fundamental principles, trade-offs, and internals of distributed storage, streaming, and database engines.',
      specifications: 'Format: Paperback | Pages: 616 | Publisher: O\'Reilly Media',
      price: 2499,
      originalPrice: 3200,
      discountPercent: 22,
      stock: 45,
      rating: 4.96,
      reviewCount: 512,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'O\'Reilly Media',
      categorySlug: 'books',
      images: [
        'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['Paperback', 'eBook'],
    },
    {
      name: 'Sapiens: A Brief History of Humankind by Yuval Noah Harari',
      slug: 'sapiens-a-brief-history-of-humankind',
      description: 'Explore how Homo sapiens conquered Earth through cognitive revolutions, agricultural evolution, and modern technology in this world-renowned bestseller.',
      specifications: 'Format: Paperback | Pages: 448 | Publisher: Harper Perennial',
      price: 599,
      originalPrice: 799,
      discountPercent: 25,
      stock: 120,
      rating: 4.9,
      reviewCount: 1150,
      isFeatured: true,
      isBestSeller: true,
      isFlashDeal: false,
      brand: 'Harper Perennial',
      categorySlug: 'books',
      images: [
        'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800&auto=format&fit=crop&q=80',
      ],
      colors: [],
      sizes: ['Paperback', 'Hardcover'],
    },
  ];

  for (const prod of products) {
    const category = createdCategories[prod.categorySlug];
    if (!category) continue;

    const createdProd = await prisma.product.create({
      data: {
        name: prod.name,
        slug: prod.slug,
        description: prod.description,
        specifications: prod.specifications,
        price: prod.price,
        originalPrice: prod.originalPrice,
        discountPercent: prod.discountPercent,
        stock: prod.stock,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        isFeatured: prod.isFeatured,
        isBestSeller: prod.isBestSeller,
        isFlashDeal: prod.isFlashDeal,
        flashDealEnd: prod.flashDealEnd,
        brand: prod.brand,
        categoryId: category.id,
      },
    });

    // Create product images
    for (let i = 0; i < prod.images.length; i++) {
      await prisma.productImage.create({
        data: {
          productId: createdProd.id,
          url: prod.images[i],
          isPrimary: i === 0,
        },
      });
    }

    // Create color variants
    for (const color of prod.colors) {
      await prisma.productVariant.create({
        data: {
          productId: createdProd.id,
          type: 'Color',
          value: color,
          stock: Math.floor(prod.stock / (prod.colors.length || 1)),
        },
      });
    }

    // Create size variants
    for (const size of prod.sizes) {
      await prisma.productVariant.create({
        data: {
          productId: createdProd.id,
          type: 'Size',
          value: size,
          stock: Math.floor(prod.stock / (prod.sizes.length || 1)),
        },
      });
    }

    // Add sample customer reviews
    await prisma.review.create({
      data: {
        productId: createdProd.id,
        userId: customer1.id,
        rating: 5,
        title: 'Outstanding quality and fast delivery!',
        comment: `Extremely happy with my ${prod.name}. The build quality exceeded my expectations! Easy-Cart shipped it so quickly.`,
        status: 'APPROVED',
      },
    });

    await prisma.review.create({
      data: {
        productId: createdProd.id,
        userId: customer2.id,
        rating: 4,
        title: 'Great value for money',
        comment: 'Super crisp design and works exactly as described. Would definitely recommend to friends.',
        status: 'APPROVED',
      },
    });
  }

  // 7. Create Sample Order in INR
  const sampleProduct = await prisma.product.findFirst({ where: { slug: 'dyson-supersonic-hair-dryer-strawberry-bronze' } });
  if (sampleProduct) {
    const order = await prisma.order.create({
      data: {
        orderNumber: 'EC-948123',
        userId: customer1.id,
        status: 'DELIVERED',
        totalAmount: 34900,
        discountAmount: 2000,
        shippingFee: 0,
        taxAmount: 2632,
        grandTotal: 35532,
        paymentMethod: 'CARD',
        paymentStatus: 'PAID',
        trackingNumber: 'TRK-9821-EXP',
        estimatedDelivery: '3 Days',
        shippingAddress: JSON.stringify({
          fullName: 'Alex Johnson',
          phone: '+91 98123 45678',
          streetAddress: 'Flat 402, Green Glen Layout, Bellandur',
          city: 'Bengaluru',
          state: 'Karnataka',
          postalCode: '560103',
          country: 'India',
        }),
      },
    });

    await prisma.orderItem.create({
      data: {
        orderId: order.id,
        productId: sampleProduct.id,
        productName: sampleProduct.name,
        productPrice: sampleProduct.price,
        selectedColor: 'Strawberry Bronze / Blush Pink',
        quantity: 1,
        subtotal: 34900,
      },
    });
  }

  console.log(`Database successfully seeded with ${products.length} products (including Dyson products!) in Indian Rupees (₹)!`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
